<?php

namespace ManaPHP\Application;

class Provider extends \ManaPHP\Di\Provider
{
    protected $definitions
        = [
            'locale'           => 'ManaPHP\I18n\Locale',
            'eventManager'     => 'ManaPHP\Event\Manager',
            'aopManager'       => 'ManaPHP\Aop\Manager',
            'poolManager'      => 'ManaPHP\Pool\Manager',
            'alias'            => 'ManaPHP\Alias',
            'dotenv'           => 'ManaPHP\Configuration\Dotenv',
            'config'           => 'ManaPHP\Config',
            'settings'         => 'ManaPHP\Configuration\Settings\Adapter\Redis',
            'invoker'          => 'ManaPHP\Controller\Invoker',
            'modelMetadata'    => 'ManaPHP\Data\Db\Model\Metadata',
            'validator'        => 'ManaPHP\Validating\Validator',
            'crypt'            => 'ManaPHP\Security\Crypt',
            'logger'           => 'ManaPHP\Logging\Logger\Adapter\File',
            'renderer'         => 'ManaPHP\Html\Renderer',
            'assetBundle'      => 'ManaPHP\Html\Renderer\AssetBundle',
            'cache'            => 'ManaPHP\Caching\Cache\Adapter\Redis',
            'httpClient'       => ['class' => 'ManaPHP\Http\Client', 'engine' => 'ManaPHP\Http\Client\Engine\Curl'],
            'restClient'       => ['class' => 'ManaPHP\Http\Client', 'engine' => 'ManaPHP\Http\Client\Engine\Fopen'],
            'downloader'       => 'ManaPHP\Http\Downloader',
            'paginator'        => 'ManaPHP\Data\Paginator',
            'msgQueue'         => 'ManaPHP\Messaging\Queue\Adapter\Redis',
            'swordCompiler'    => 'ManaPHP\Html\Renderer\Engine\Sword\Compiler',
            'htmlPurifier'     => 'ManaPHP\Html\Purifier',
            'db'               => 'ManaPHP\Data\Db',
            'redis'            => 'ManaPHP\Data\Redis',
            'redisCache'       => '@redis',
            'redisDb'          => '@redis',
            'redisBroker'      => '@redis',
            'mongodb'          => 'ManaPHP\Data\Mongodb',
            'translator'       => 'ManaPHP\I18n\Translator',
            'relationManager'  => 'ManaPHP\Data\Relation\Manager',
            'mailer'           => 'ManaPHP\Mailing\Mailer\Adapter\Smtp',
            'bosClient'        => 'ManaPHP\Bos\Client',
            'wspClient'        => 'ManaPHP\Ws\Pushing\Client',
            'identity'         => 'ManaPHP\Identifying\Identity',
            'coroutineManager' => 'ManaPHP\Coroutine\Manager',
            'jwt'              => 'ManaPHP\Token\Jwt',
            'scopedJwt'        => 'ManaPHP\Token\ScopedJwt',
            'wsClient'         => 'ManaPHP\Ws\Client',
            'pubSub'           => 'ManaPHP\Messaging\PubSub\Adapter\Redis',
            'dataDump'         => 'ManaPHP\Debugging\DataDump',
            'cliRunner'        => 'ManaPHP\Cli\Runner',
            'chatClient'       => 'ManaPHP\Ws\Chatting\Client',
            'amqpClient'       => 'ManaPHP\Amqp\Client',
            'amqpRpc'          => 'ManaPHP\Rpc\Amqp\Client',
            'tracerManager'    => 'ManaPHP\Tracer\Manager',

            'backtracePlugin' => 'ManaPHP\Plugins\BacktracePlugin',
            'debuggerPlugin'  => 'ManaPHP\Plugins\DebuggerPlugin',
            'fiddlerPlugin'   => 'ManaPHP\Plugins\FiddlerPlugin',
            'loggerPlugin'    => 'ManaPHP\Plugins\LoggerPlugin',
        ];
}