<?php

namespace Tests;

use ManaPHP\Curl\Easy;
use ManaPHP\Di\FactoryDefault;
use PHPUnit\Framework\TestCase;

class HttpClientTest extends TestCase
{
    protected $_di;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->_di = new FactoryDefault();
        $this->_di->logger->removeAppender('file');
    }

    public function test_get()
    {
        $easy = new Easy();

        $response = $easy->get(['http://apis.juhe.cn/ip/ip2addr', 'ip' => 'www.baidu.com', 'key' => 'appkey']);
        $this->assertEquals(200, $response->http_code);
        $this->assertEquals(101, $response->getJsonBody()['resultcode']);
    }

    public function test_post()
    {
        $easy = new Easy();

        $response = $easy->post(['http://lxb.baidu.com/', 'uid' => 0, 'f' => 4], ['r' => 'www.xxx.com']);
        $this->assertEquals(200, $response->http_code);
    }

    public function test_delete()
    {
        $easy = new Easy();
        $easy->delete('http://www.baidu.com/', []);
    }

    public function test_put()
    {
        $easy = new Easy();
        $easy->put('http://www.baidu.com/', [], []/*,['proxy'=>'127.0.0.1:8888']*/);
    }

    public function test_patch()
    {
        $easy = new Easy();
        $easy->patch('http://www.baidu.com', [], []/*,['proxy'=>'127.0.0.1:8888']*/);
    }
}