<?php
namespace Tests;

use ManaPHP\Di\FactoryDefault;
use ManaPHP\Curl\Easy;
use PHPUnit\Framework\TestCase;

class DummyEasy extends Easy
{
    public $type;
    public $url;
    public $data;
    public $headers;
    public $options;
    public $httpCode = 200;

    public function _request($type, $url, $data, $headers, $options)
    {
        $this->type = $type;
        $this->url = $url;
        $this->data = $data;
        $this->headers = $headers;
        $this->options = $options;
        return $this->httpCode;
    }
}

class HttpClientTest extends TestCase
{
    protected $_di;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->_di = new FactoryDefault();
    }

    public function test_buildUrl()
    {
        $easy = new DummyEasy();

        $easy->get('http://www.example.com/');
        $this->assertEquals('http://www.example.com/', $easy->url);

        $easy->get('http://www.example.com/?page=1');
        $this->assertEquals('http://www.example.com/?page=1', $easy->url);

        $easy->get(['http://www.example.com/', 'page' => 1]);
        $this->assertEquals('http://www.example.com/?page=1', $easy->url);

        $easy->get('http://www.example.com/?page=1&size=10');
        $this->assertEquals('http://www.example.com/?page=1&size=10', $easy->url);

        $easy->get(['http://www.example.com/', 'page' => 1, 'size' => 10]);
        $this->assertEquals('http://www.example.com/?page=1&size=10', $easy->url);

        $easy->get(['http://www.example.com/?page=1', 'size' => 10]);
        $this->assertEquals('http://www.example.com/?page=1&size=10', $easy->url);

        $easy->get(['http://www.example.com/', 'keyword' => '中国']);
        $this->assertEquals('http://www.example.com/?keyword=%E4%B8%AD%E5%9B%BD', $easy->url);
    }

    public function test_get()
    {
        $easy = new Easy();

        $response = $easy->get(['http://apis.juhe.cn/ip/ip2addr', 'ip' => 'www.baidu.com', 'key' => 'appkey']);
        $this->assertEquals(200, $response->http_code);
        $this->assertEquals(101, $response->getJsonBody()['resultcode']);
    }

    public function test_post()
    {
        $easy = new Easy();

        $response = $easy->post(['http://lxb.baidu.com/', 'uid' => 0, 'f' => 4], ['r' => 'www.xxx.com']);
        $this->assertEquals(200, $response->http_code);
    }

    public function test_delete()
    {
        $easy = new Easy();
        $easy->delete('http://www.baidu.com/', []);
    }

    public function test_put()
    {
        $easy = new Easy();
        $easy->put('http://www.baidu.com/', [], []/*,['proxy'=>'127.0.0.1:8888']*/);
    }

    public function test_patch()
    {
        $easy = new Easy();
        $easy->patch('http://www.baidu.com', [], []/*,['proxy'=>'127.0.0.1:8888']*/);
    }
}