<?php
namespace Tests;

use ManaPHP\Di;
use ManaPHP\Dom\Document;

class DomDocumentTest extends \PHPUnit_Framework_TestCase
{
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        new Di\FactoryDefault();
    }

    public function test_load()
    {
        $document = new Document();

        $this->assertNotEmpty($document->load('https://www.baidu.com')->getString());
        $this->assertNotEmpty($document->load(__DIR__ . '/Dom/sample.html')->getString());
        $this->assertEquals('<div></div>', $document->load('<div></div>')->getString());
    }

    public function test_loadFile()
    {
        $document = new Document();
        $this->assertNotEmpty($document->loadFile(__DIR__ . '/Dom/sample.html')->getString());
    }

    public function test_loadUrl()
    {
        $document = new Document();
        $this->assertNotEmpty($document->loadUrl('https://www.baidu.com')->getString());
    }

    public function test_loadString()
    {
        $document = new Document();
        $this->assertEquals('<div></div>', $document->loadString('<div></div>')->getString());
    }
}