<?php

namespace Tests;

use ManaPHP\Di\FactoryDefault;
use ManaPHP\Renderer\Html;
use PHPUnit\Framework\TestCase;

class RendererHtmlTest extends TestCase
{
    protected function setUp()/* The :void return type declaration that should be here would cause a BC issue */
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        new FactoryDefault();
    }

    public function test_select()
    {
        $html = new Html();
        $base = ['options' => ['' => 'all', '0' => 'baidu', '1' => 'google']];

        //no value
        $data = $base;
        $this->assertEquals(
            <<<EOT

  <select>
    <option value="" selected>all</option>
    <option value="0">baidu</option>
    <option value="1">google</option>
  </select>

EOT
            , $html->render('select', $data)
        );

        //value=''
        $data = $base;
        $data['value'] = '';
        $this->assertEquals(
            <<<EOT

  <select>
    <option value="" selected>all</option>
    <option value="0">baidu</option>
    <option value="1">google</option>
  </select>

EOT
            , $html->render('select', $data)
        );

        //value=1
        $data = $base;
        $data['value'] = 1;
        $this->assertEquals(
            <<<EOT

  <select>
    <option value="">all</option>
    <option value="0">baidu</option>
    <option value="1" selected>google</option>
  </select>

EOT
            , $html->render('select', $data)
        );

        //value='1'
        $data = $base;
        $data['value'] = '1';
        $this->assertEquals(
            <<<EOT

  <select>
    <option value="">all</option>
    <option value="0">baidu</option>
    <option value="1" selected>google</option>
  </select>

EOT
            , $html->render('select', $data)
        );

        //name='engine' class='engine_select'
        $data = $base;
        $data['name'] = 'engine';
        $data['class'] = 'engine_select';
        $data['value'] = '1';
        $this->assertEquals(
            <<<EOT

  <select name="engine" class="engine_select">
    <option value="">all</option>
    <option value="0">baidu</option>
    <option value="1" selected>google</option>
  </select>

EOT
            , $html->render('select', $data)
        );
    }
}