<!doctype html>
<!--suppress ALL -->
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>ManaPHP Debugger</title>
  <link rel="stylesheet" href="http://cdn.bootcss.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <!--[if lt IE 9]>
  <script src="http://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->
  <style>
    #tab_global tr td:nth-child(1) {
      width: 5%;
    }

    #tab_global tr td:nth-child(2) {
      width: 20%;
    }

    body {
      overflow-y: scroll;
    }

    table pre {
      border: none;
      padding: 0;
      margin: 0;
      background-color: transparent;
      white-space: pre-wrap;
      word-wrap: break-word;
      max-height: 80px;
    }

    #tab_components pre {
      max-height: 200px;
    }

    .debugger {
      position: fixed;
      right: 80px;
      top: 80px;
      z-index: 1000000;
      min-width: 80px;
      text-align: center;
      border: 1px solid blue;
      border-radius: 3px;
    }

    .debugger a {
      display: block;
      color: red;
      text-decoration: none;
    }
  </style>
</head>
<body>
<div class="container" id="app">
  <ul class="nav nav-tabs">
    <li><a href="#tab_basic" data-toggle="tab">Basic</a></li>
    <li><a href="#tab_dump" data-toggle="tab">Dump</a></li>
    <li><a href="#tab_components" data-toggle="tab">Components</a></li>
    <li><a href="#tab_view" data-toggle="tab">View</a></li>
    <li><a href="#tab_configure" data-toggle="tab">Configure</a></li>
    <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Global <b class="caret"></b></a>
      <ul class="dropdown-menu">
        <li><a data-toggle="tab" @click="global_type='request'" href="#tab_global">REQUEST</a></li>
        <li><a data-toggle="tab" @click="global_type='get'" href="#tab_global">GET</a></li>
        <li><a data-toggle="tab" @click="global_type='post'" href="#tab_global">POST</a></li>
        <li><a data-toggle="tab" @click="global_type='session'" href="#tab_global">SESSION</a></li>
        <li><a data-toggle="tab" @click="global_type='cookie'" href="#tab_global">COOKIE</a></li>
        <li><a data-toggle="tab" @click="global_type='server'" href="#tab_global">SERVER</a></li>
      </ul>
    </li>
    <li><a href="#tab_log" data-toggle="tab">Log</a></li>
    <li><a href="#tab_sql" data-toggle="tab">SQL</a></li>
    <li><a href="#tab_included_files" data-toggle="tab">IncludedFiles</a></li>
  </ul>
  <div class="debugger"><a :href="basic.request_url" :title="basic.request_url" target="_self">ReqSrc</a></div>
  <div class="tab-content">
    <div class="tab-pane" id="tab_basic">
      <h4>Basic Information</h4>
      <table class="table table-striped table-bordered table-condensed">
        <thead>
        <tr>
          <td style="width: 5%">#</td>
          <td>name</td>
          <td>value</td>
        </tr>
        </thead>
        <tbody>
        <tr v-for="(value, name, index) in basic">
          <td>{{index}}</td>
          <td>{{name}}</td>
          <td>{{value}}</td>
        </tr>
        </tbody>
      </table>
    </div>
    <div class="tab-pane" id="tab_dump">
      <h4>Dump Data({{dump.length}})</h4>
      <table class="table table-striped table-bordered table-condensed">
        <thead>
        <tr>
          <td width="5%">#</td>
          <td width="15%">location</td>
          <td>name</td>
          <td>value</td>
        </tr>
        </thead>
        <tbody>
        <tr v-for="(item, index) in dump">
          <td>{{index}}</td>
          <td title="{{item.file}}:{{item.line}}">{{item.base_name}}:{{item.line}}</td>
          <td>{{item.name}}</td>
          <td title="{{item.value|json 4}}">
            <pre>{{item.value|json 4}}</pre>
          </td>
        </tr>
        </tbody>
      </table>
    </div>
    <div class="tab-pane" id="tab_components">
      <h4>Dump Data({{dump.length}})</h4>
      <table class="table table-striped table-bordered table-condensed">
        <thead>
        <tr>
          <td width="5%">#</td>
          <td width="10%">name</td>
          <td width="20%">type</td>
          <td>value</td>
        </tr>
        </thead>
        <tbody>
        <tr v-for="(item, index) in components">
          <td>{{index}}</td>
          <td title="{{item.name}}">{{item.name}}</td>
          <td>{{item.class}}</td>
          <td title="{{item.properties|json 4}}">
            <pre>{{item.properties|json 4}}</pre>
          </td>
        </tr>
        </tbody>
      </table>
    </div>
    <div class="tab-pane" id="tab_view">
      <h4>Renderer Files({{view.length}})</h4>
      <table class="table table-striped table-bordered table-condensed">
        <thead>
        <tr>
          <td style="width: 5%">#</td>
          <td style="width: 20%">file</td>
          <td>vars</td>
        </tr>
        </thead>
        <tbody>
        <tr v-for="(item, index) in view">
          <td>{{index}}</td>
          <td title="{{item.file}}">{{item.base_name}}</td>
          <td>
            <pre>{{item.vars|json 4}}</pre>
          </td>
        </tr>
        </tbody>
      </table>
    </div>
    <div class="tab-pane" id="tab_configure">
      <h4>Configure</h4>
      <table class="table table-striped table-bordered table-condensed">
        <thead>
        <tr>
          <td style="width: 5%">#</td>
          <td>name</td>
          <td>value</td>
        </tr>
        </thead>
        <tbody>
        <tr v-for="(value,name, index) in configure">
          <td>{{index}}</td>
          <td>{{name}}</td>
          <td title="{{value|json 4}}">
            <pre>{{value|json 4}}</pre>
          </td>
        </tr>
        </tbody>
      </table>
    </div>
    <div class="tab-pane" id="tab_global">
      <h4><span class="text-uppercase">{{global_type}}</span> Data</h4>
      <table class="table table-striped table-bordered table-condensed">
        <thead>
        <tr>
          <td style="width: 5%">#</td>
          <td style="width: 15%">name</td>
          <td>value</td>
        </tr>
        </thead>
        <tbody>
        <tr v-for="(value, name, index) in data[global_type]">
          <td>{{ index }}</td>
          <td>{{ name }}</td>
          <td>{{ value }}</td>
        </tr>
        </tbody>
      </table>
    </div>
    <div class="tab-pane" id="tab_log">
      <h4>Log Messages
        <small><select v-model="logger.level" title="">
            <option v-for="(intLevel,strLevel) in logger.levels" :value="intLevel">{{strLevel}}</option>
          </select></small>
      </h4>
      <table class="table table-striped table-bordered table-condensed">
        <thead>
        <tr>
          <td>#</td>
          <td>message</td>
        </tr>
        </thead>
        <tbody>
        <tr v-for="(item, index) in logger.log" v-if="logger.levels[item.level] <= logger.level">
          <td>{{index}}</td>
          <td>{{item.message}}</td>
        </tr>
        </tbody>
      </table>
    </div>
    <div class="tab-pane" id="tab_sql">

      <h4>SQL Statements({{sql.count}})
        <small><label><input type="checkbox" checked v-model="log_checked_executed">Executed</label></small>
      </h4>
      <div v-show="log_checked_executed">
        <table class="table table-striped table-bordered table-condensed">
          <thead>
          <tr>
            <td style="width: 5%">#</td>
            <td style="width: 8%">rows</td>
            <td>executed sql</td>
            <td>time</td>
          </tr>
          </thead>
          <tbody>
          <tr v-for="(item, index) in sql.executed" title="{{item|json 4}}">
            <td>{{index}}</td>
            <td>{{item.row_count}}</td>
            <td>{{item.emulated}}</td>
            <td>{{item.time}}</td>

          </tr>
          </tbody>
        </table>
      </div>
      <div v-show="!log_checked_executed">
        <table class="table table-striped table-bordered table-condensed">
          <thead>
          <tr>
            <td style="width: 5%">#</td>
            <td style="width: 8%">count</td>
            <td>prepared sql</td>
          </tr>
          </thead>
          <tbody>
          <tr v-for="(count, sql, index) in sql.prepared">
            <td>{{index}}</td>
            <td>{{count}}</td>
            <td>{{sql}}</td>
          </tr>
          </tbody>
        </table>
      </div>
    </div>
    <div class="tab-pane" id="tab_included_files">
      <h4>IncludedFiles({{included_files_computed.length}}) <label><input type="checkbox" v-model="included_files_application_only">
          <small>Ignore Framework Files</small>
          </input></label></h4>
      <table class="table table-striped table-bordered table-condensed">
        <thead>
        <tr>
          <td style="width: 5%">#</td>
          <td>file</td>
        </tr>
        </thead>
        <tbody>
        <tr v-for="(file, index) in included_files_computed">
          <td>{{index}}</td>
          <td>{{file}}</td>
        </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>
<script src="http://cdn.bootcss.com/jquery/1.11.3/jquery.min.js"></script>
<script src="http://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src='http://cdn.bootcss.com/vue/2.2.4/vue.min.js'></script>

<?php
$data['included_files'] = get_included_files();
$data['request'] = $_REQUEST;
$data['get'] = $_GET;
$data['post'] = $_POST;
$data['cookie'] = $_COOKIE;
$data['session'] = isset($_SESSION) ? $_SESSION : [];
$data['server'] = $_SERVER;
unset($data['server']['PATH']);
?>
<!--suppress JSUnresolvedFunction -->
<script>
    data =<?=json_encode($data, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT | JSON_HEX_TAG)?>;

    data['included_files_application'] = [];
    data['included_files_application_only'] = true;
    data['log_checked_executed'] = true;
    data['global_type'] = 'request';

    $("a[href='#<?=count($data['exception']) === 0 ? 'tab_basic' : 'tab_exception'?>']").tab('show');

    var app = new Vue({
        el: '#app',
        data: data,
        computed: {
            included_files_computed: function () {
                if (data['included_files_application_only']) {
                    var computed = [];
                    for (var file of data['included_files']) {
                        if (file.indexOf('ManaPHP') < 0 && file.indexOf('framework') < 0) {
                            computed.push(file);
                        }
                    }
                    return computed;
                } else {
                    return data['included_files'];
                }
            }
        }
    })
</script>
</body>
</html>