version : "3.8"
services :
  user-fpm :
    image : manaphp/php80:220320
    volumes :
      - .:/var/www/html
      - ./docker/fpm/etc/fpm.conf:/etc/php/fpm.conf
      - ./docker/fpm/etc/php.ini:/etc/php/php.ini
      - ./runtime/fpm/:/var/log/php
      - ../framework:/var/www/framework
    command : bash /var/www/html/docker/fpm/bootstrap.sh
    restart : always
  user-nginx :
    image : nginx:1.19.6
    volumes :
      - /usr/share/zoneinfo/PRC:/etc/localtime
      - .:/var/www/html
      - ./docker/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/docker-entrypoint.sh:/docker-entrypoint.sh
      - ./runtime/nginx:/var/log/nginx
    entrypoint : /docker-entrypoint.sh nginx -g "daemon off;"
    ports :
      - ${WEB_PORT}:80
    restart : always