version: "2"
services:
  admin:
    image: manaphp/php74:4.1
    volumes:
      - ./:/var/www/html
      - /data/volumes/${COMPOSE_PROJECT_NAME}/admin/data:/var/www/html/data
      - /data/volumes/${COMPOSE_PROJECT_NAME}/admin/tmp:/var/www/html/tmp
      - ../../ManaPHP:/var/www/html/vendor/manaphp/framework
    command: php -d opcache.enable_cli=on /var/www/html/public/index.php
    ports:
      - ${WEB_PORT}:9501
    restart: always
