<?php
defined('UNIT_TESTS_ROOT') || require __DIR__ . '/bootstrap.php';

class HttpSessionAdapterFileTest extends TestCase
{
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $di = new \ManaPHP\Di\FactoryDefault();
        $di->alias->set('@data', sys_get_temp_dir());
    }

    public function test_open()
    {
        $session_id = md5(microtime(true) . mt_rand());
        $adapter = new \ManaPHP\Http\Session\Adapter\File();

        $this->assertTrue($adapter->open('', $session_id));
    }

    public function test_close()
    {
        $session_id = md5(microtime(true) . mt_rand());
        $adapter = new \ManaPHP\Http\Session\Adapter\File();

        $this->assertTrue($adapter->close());
    }

    public function test_read()
    {
        $session_id = md5(microtime(true) . mt_rand());
        $adapter = new \ManaPHP\Http\Session\Adapter\File();

        $adapter->open($session_id, '');
        $this->assertEquals('', $adapter->read($session_id));

        $adapter->write($session_id, 'manaphp');
        $this->assertEquals('manaphp', $adapter->read($session_id));
    }

    public function test_write()
    {
        $session_id = md5(microtime(true) . mt_rand());
        $adapter = new \ManaPHP\Http\Session\Adapter\File();

        $adapter->write($session_id, '');
        $this->assertEquals('', $adapter->read($session_id));

        $adapter->write($session_id, 'manaphp');
        $this->assertEquals('manaphp', $adapter->read($session_id));
    }

    public function test_destory()
    {
        $session_id = md5(microtime(true) . mt_rand());
        $adapter = new \ManaPHP\Http\Session\Adapter\File();
        $this->assertTrue($adapter->destroy($session_id));

        $adapter->write($session_id, 'manaphp');
        $this->assertEquals('manaphp', $adapter->read($session_id));
        $this->assertTrue($adapter->destroy($session_id));

        $this->assertEquals('', $adapter->read($session_id));
    }

    public function test_gc()
    {
        $session_id = md5(microtime(true) . mt_rand());
        $adapter = new \ManaPHP\Http\Session\Adapter\File();
        $this->assertTrue($adapter->gc(100));
    }
}