<?php
defined('UNIT_TESTS_ROOT') || require __DIR__ . '/bootstrap.php';

class MvcViewRendererEngineSwordTest extends TestCase
{
    /**
     * @var \ManaPHP\Mvc\View\Renderer\Engine\Sword
     */
    public $sword;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->sword = new \ManaPHP\Mvc\View\Renderer\Engine\Sword();
    }

    public function test_Append()
    {
        $source = <<<'EOT'
@append
EOT;
        $compiled = <<<'EOT'
<?php $view->appendSection(); ?>
EOT;
        $this->assertEquals($compiled, $this->sword->compileString($source));
    }

    public function test_Break()
    {
        $source = <<<'EOT'
@break
EOT;
        $compiled = <<<'EOT'
<?php break;?>
EOT;
        $this->assertEquals($compiled, $this->sword->compileString($source));
    }

    public function test_Comments()
    {
        $source = <<<'EOT'
{{-- comments --}}
EOT;
        $compiled = <<<'EOT'
<?php /* comments */ ?>
EOT;
        $this->assertEquals($compiled, $this->sword->compileString($source));
    }

    public function test_Continue()
    {
        $source = <<<'EOT'
@continue
EOT;
        $compiled = <<<'EOT'
<?php continue;?>
EOT;
        $this->assertEquals($compiled, $this->sword->compileString($source));
    }

    public function test_EscapedEchos()
    {
        $source = <<<'EOT'
Welcome, {{ $name or ManaPHP }} !
EOT;
        $compiled = <<<'EOT'
Welcome, <?php echo $view->escape(isset($name) ? $name : ManaPHP); ?> !
EOT;
        $this->assertEquals($compiled, $this->sword->compileString($source));
    }

    public function test_RawEchos()
    {
        $source = <<<EOT
{!! '\'"<>&' !!}
EOT;

        $compiled = <<<EOT
<?php echo '\'"<>&'; ?>
EOT;
        $this->assertEquals($compiled, $this->sword->compileString($source));
    }

    public function test_Else()
    {
        $source = <<<'EOT'
@else
EOT;
        $compiled = <<<'EOT'
<?php else: ?>
EOT;
        $this->assertEquals($compiled, $this->sword->compileString($source));
    }

    public function test_Elseif()
    {
        $source = <<<'EOT'
@elseif (true)
EOT;
        $compiled = <<<'EOT'
<?php elseif(true): ?>
EOT;
        $this->assertEquals($compiled, $this->sword->compileString($source));
    }

    public function test_Empty()
    {
        $source = <<<'EOT'
@empty
EOT;
        $compiled = <<<'EOT'
<?php endforeach; if ($__empty_0): ?>
EOT;
        $this->assertEquals($compiled, $this->sword->compileString($source));
    }

    public function test_EndFor()
    {
        $source = <<<'EOT'
@endfor
EOT;
        $compiled = <<<'EOT'
<?php endfor; ?>
EOT;
        $this->assertEquals($compiled, $this->sword->compileString($source));
    }

    public function test_EndForeach()
    {
        $source = <<<'EOT'
@endforeach
EOT;
        $compiled = <<<'EOT'
<?php endforeach; ?>
EOT;
        $this->assertEquals($compiled, $this->sword->compileString($source));
    }

    public function test_Endforelse()
    {
        $source = <<<'EOT'
@endforelse
EOT;
        $compiled = <<<'EOT'
<?php endif; ?>
EOT;
        $this->assertEquals($compiled, $this->sword->compileString($source));
    }

    public function test_Endif()
    {
        $source = <<<'EOT'
@endif
EOT;
        $compiled = <<<'EOT'
<?php endif; ?>
EOT;
        $this->assertEquals($compiled, $this->sword->compileString($source));
    }

    public function test_EndPush()
    {
        $source = <<<'EOT'
@endpush
EOT;
        $compiled = <<<'EOT'
<?php $view->appendSection(); ?>
EOT;
        $this->assertEquals($compiled, $this->sword->compileString($source));
    }

    public function test_EndSection()
    {
        $source = <<<'EOT'
@endSection
EOT;
        $compiled = <<<'EOT'
<?php $view->stopSection(); ?>
EOT;
        $this->assertEquals($compiled, $this->sword->compileString($source));
    }

    public function test_EndWhile()
    {
        $source = <<<'EOT'
@endwhile
EOT;
        $compiled = <<<'EOT'
<?php endwhile; ?>
EOT;
        $this->assertEquals($compiled, $this->sword->compileString($source));
    }

    public function test_For()
    {
        $source = <<<'EOT'
@for ($i = 0; $i < 10; $i++)
EOT;
        $compiled = <<<'EOT'
<?php for($i = 0; $i < 10; $i++): ?>
EOT;
        $this->assertEquals($compiled, $this->sword->compileString($source));
    }

    public function test_Foreach()
    {
        $source = <<<'EOT'
@foreach ($users as $user)
EOT;
        $compiled = <<<'EOT'
<?php foreach($users as $user): ?>
EOT;
        $this->assertEquals($compiled, $this->sword->compileString($source));
    }

    public function test_ForElse()
    {
        $source = <<<'EOT'
@forelse($users as $user)
EOT;
        $compiled = <<<'EOT'
<?php $__empty_1 = true; foreach($users as $user): $__empty_1 = false; ?>
EOT;
        $this->assertEquals($compiled, $this->sword->compileString($source));
    }

    public function test_If()
    {
        $source = <<<'EOT'
@if (count($lists) > 1)
EOT;
        $compiled = <<<'EOT'
<?php if(count($lists) > 1): ?>
EOT;
        $this->assertEquals($compiled, $this->sword->compileString($source));
    }

    public function test_Include()
    {
        $source = <<<'EOT'
@include('footer')
EOT;
        $compiled = <<<'EOT'
<?php $view->partial('footer'); ?>
EOT;
        $this->assertEquals($compiled, $this->sword->compileString($source));

        $source = <<<'EOT'
@include('footer',['p1'=>1,'p2'=>2])
EOT;
        $compiled = <<<'EOT'
<?php $view->partial('footer',['p1'=>1,'p2'=>2]); ?>
EOT;
        $this->assertEquals($compiled, $this->sword->compileString($source));
    }

    public function test_Overwrite()
    {
        $source = <<<'EOT'
@overwrite
EOT;
        $compiled = <<<'EOT'
<?php $view->stopSection(true); ?>
EOT;
        $this->assertEquals($compiled, $this->sword->compileString($source));
    }

    public function test_Partial()
    {
        $source = <<<'EOT'
@include('footer')
EOT;
        $compiled = <<<'EOT'
<?php $view->partial('footer'); ?>
EOT;
        $this->assertEquals($compiled, $this->sword->compileString($source));

        $source = <<<'EOT'
@include('footer',['p1'=>1,'p2'=>2])
EOT;
        $compiled = <<<'EOT'
<?php $view->partial('footer',['p1'=>1,'p2'=>2]); ?>
EOT;
        $this->assertEquals($compiled, $this->sword->compileString($source));
    }

    public function test_Push()
    {
        $source = <<<'EOT'
@push('scripts')
EOT;
        $compiled = <<<'EOT'
<?php $view->startSection('scripts'); ?>
EOT;
        $this->assertEquals($compiled, $this->sword->compileString($source));
    }

    public function test_Section()
    {
        $source = <<<'EOT'
@section('scripts')
EOT;
        $compiled = <<<'EOT'
<?php $view->startSection('scripts'); ?>
EOT;
        $this->assertEquals($compiled, $this->sword->compileString($source));
    }

    public function test_Stack()
    {
        $source = <<<'EOT'
@stack('scripts')
EOT;
        $compiled = <<<'EOT'
<?php echo $view->getSection('scripts'); ?>
EOT;
        $this->assertEquals($compiled, $this->sword->compileString($source));

        $source = <<<'EOT'
@stack('scripts','')
EOT;
        $compiled = <<<'EOT'
<?php echo $view->getSection('scripts',''); ?>
EOT;
        $this->assertEquals($compiled, $this->sword->compileString($source));
    }

    public function test_Stop()
    {
        $source = <<<'EOT'
@stop
EOT;
        $compiled = <<<'EOT'
<?php $view->stopSection(); ?>
EOT;
        $this->assertEquals($compiled, $this->sword->compileString($source));
    }

    public function test_While()
    {
        $source = <<<'EOT'
@while (true)
EOT;
        $compiled = <<<'EOT'
<?php while(true): ?>
EOT;
        $this->assertEquals($compiled, $this->sword->compileString($source));
    }

    public function test_Yield()
    {
        $source = <<<'EOT'
@yield('scripts')
EOT;
        $compiled = <<<'EOT'
<?php echo $view->getSection('scripts'); ?>
EOT;
        $this->assertEquals($compiled, $this->sword->compileString($source));

        $source = <<<'EOT'
@yield('scripts','')
EOT;
        $compiled = <<<'EOT'
<?php echo $view->getSection('scripts',''); ?>
EOT;
        $this->assertEquals($compiled, $this->sword->compileString($source));
    }

    public function test_Layout()
    {
        $source = <<<'EOT'
@layout(false)
EOT;
        $compiled = <<<'EOT'
<?php $view->setLayout(false); ?>
EOT;
        $this->assertEquals($compiled, $this->sword->compileString($source));

        $source = <<<'EOT'
@layout('table')
EOT;
        $compiled = <<<'EOT'
<?php $view->setLayout('table'); ?>
EOT;
        $this->assertEquals($compiled, $this->sword->compileString($source));
    }

    public function test_Content()
    {
        $source = <<<'EOT'
@content
EOT;
        $compiled = <<<'EOT'
<?php echo $view->getContent(); ?>
EOT;
        $this->assertEquals($compiled, $this->sword->compileString($source));
    }

    public function test_Php()
    {
        $source = <<<'EOT'
@php
EOT;
        $compiled = <<<'EOT'
<?php 
EOT;
        $this->assertEquals($compiled, $this->sword->compileString($source));
    }

    public function test_EndPhp()
    {
        $source = <<<'EOT'
@endphp
EOT;
        $compiled = <<<'EOT'
 ?>
EOT;
        $this->assertEquals($compiled, $this->sword->compileString($source));
    }


    public function test_Widget()
    {
        $source = <<<'EOT'
@widget('ad')
EOT;
        $compiled = <<<'EOT'
<?php echo $view->widget('ad'); ?>
EOT;
        $this->assertEquals($compiled, $this->sword->compileString($source));

        $source = <<<'EOT'
@widget('ad',['category_id'=>1])
EOT;
        $compiled = <<<'EOT'
<?php echo $view->widget('ad',['category_id'=>1]); ?>
EOT;
        $this->assertEquals($compiled, $this->sword->compileString($source));
    }

    public function test_Url()
    {
        $source = <<<'EOT'
@url('/')
EOT;
        $compiled = <<<'EOT'
<?php echo $di->url->get('/'); ?>
EOT;
        $this->assertEquals($compiled, $this->sword->compileString($source));

        $source = <<<'EOT'
@url('/',['id'=>100])
EOT;
        $compiled = <<<'EOT'
<?php echo $di->url->get('/',['id'=>100]); ?>
EOT;
        $this->assertEquals($compiled, $this->sword->compileString($source));
    }
}