<el-menu
        default-active="<?=action('')?>"
        class="el-menu-vertical-demo">
    <el-submenu index="right_manager">
        <template slot="title">
            <span>Right Manager</span>
        </template>
        <el-menu-item index="<?=action('/rbac/user/')?>"><a href="<?=action('/rbac/user/')?>">User</a></el-menu-item>
        <el-menu-item index="<?=action('/rbac/role/')?>"><a href="<?=action('/rbac/role/')?>">Role</a></el-menu-item>
        <el-menu-item index="<?=action('/rbac/permission/')?>"><a href="<?=action('/rbac/permission/')?>">Permission</a>
        </el-menu-item>
        <el-menu-item index="<?=action('/rbac/user_role/')?>"><a href="<?=action('/rbac/user_role/')?>">User Role</a>
        </el-menu-item>
        <el-menu-item index="<?=action('/rbac/role_permission/')?>"><a href="<?=action('/rbac/role_permission/')?>">Role
                Permission</a>
        </el-menu-item>
    </el-submenu>
    <el-submenu>
        <template slot="title" index="system_information">
            <span>System Information</span>
        </template>
        <el-menu-item index="<?=action('/index/system_information/')?>"><a href="<?=action('/index/system_information/')?>">System
                Information</a></el-menu-item>
    </el-submenu>
    <el-submenu index="log_manager">
        <template slot="title">
            <span>Log Manager</span>
        </template>
        <el-menu-item index="<?=action('/user/session/log')?>"><a href="<?=action('/user/session/log')?>">SessionLog</a>
        </el-menu-item>
    </el-submenu>
  <el-submenu index="menu_manager">
    <template slot="title">
      <span>Menu Manager</span>
    </template>
    <el-menu-item index="<?=action('/menu/group')?>"><a href="<?=action('/menu/group')?>">Menu Group</a></el-menu-item>
    <el-menu-item index="<?=action('/menu/item')?>"><a href="<?=action('/menu/item')?>">Menu Item</a></el-menu-item>
  </el-submenu>
</el-menu>
