version : "2"
services :
  ws :
    image : manaphp/php74:210801
    volumes :
      - ../:/var/www/html
      - /data/volumes/${COMPOSE_PROJECT_NAME}/ws/runtime:/var/www/html/runtime
      - ../../framework:/var/www/framework
    command : php -d opcache.enable_cli=on /var/www/html/public/index.php
    ports :
      - ${WS_PORT}:9501
    restart : always
