#!/usr/bin/env php
<?php
//require __DIR__ . '/../vendor/autoload.php';
require __DIR__ . '/../../ManaPHP/Loader.php';

$loader = new \ManaPHP\Loader();
require __DIR__ . '/app/Application.php';
$app = new \App\Cli\Application($loader);
$app->main();